//! Stable VM identity (`vm_uuid`) and the `_mist._tcp` mDNS advertisement (design 11 §2, §6).
//!
//! The `vm_uuid` is minted once on first start and persisted so it survives guest reboots — unlike
//! `boot_id` (per-mistd-start) and a share's `epoch` (per-mount), neither of which can key the
//! resolver. It is an identifier, not a secret: leaking it grants nothing without the token.
//!
//! The advert is published by dropping a static service file into avahi's watch directory. That is
//! simpler and more robust than the D-Bus entry-group API (no dbus client, survives an avahi
//! restart) and carries the live `vm_uuid`/port/share-count so the host resolves host+port+identity
//! in one mDNS shot. The TXT record is **non-secret only** — multicast cleartext on a shared
//! segment never carries the token or its fingerprint.

use std::io::Write;
use std::os::unix::fs::OpenOptionsExt;
use std::path::Path;

/// Load the persisted `vm_uuid`, minting and writing a fresh one if absent or malformed.
pub fn load_or_create_vmid(path: &Path) -> anyhow::Result<[u8; 16]> {
    if let Ok(s) = std::fs::read_to_string(path)
        && let Some(uuid) = mist_proto::vm_uuid_from_hex(s.trim())
    {
        return Ok(uuid);
    }
    // Absent or corrupt → mint. A corrupt file is overwritten (a half-written hex string from a
    // crashed first start would otherwise wedge identity forever).
    let uuid: [u8; 16] = rand::random();
    if let Some(dir) = path.parent() {
        std::fs::create_dir_all(dir)?;
    }
    let mut f = std::fs::OpenOptions::new()
        .write(true)
        .create(true)
        .truncate(true)
        .mode(0o644)
        .open(path)
        .map_err(|e| anyhow::anyhow!("writing vmid {}: {e}", path.display()))?;
    writeln!(f, "{}", mist_proto::vm_uuid_hex(&uuid))?;
    tracing::info!(path = %path.display(), uuid = %mist_proto::vm_uuid_hex(&uuid), "minted vm_uuid");
    Ok(uuid)
}

/// Render the avahi `_mist._tcp` service file. `tcp_port` is the guest's vmnet TCP listener (the
/// host dials TCP-over-vmnet; vsock is unreachable from a non-owner supervisor, design 11 §0).
pub fn avahi_service_xml(uuid: &[u8; 16], tcp_port: u16, shares: usize, kver: &str) -> String {
    // kver may contain XML-unsafe characters in pathological cases; keep only the safe subset.
    let kver: String = kver
        .chars()
        .filter(|c| c.is_ascii_alphanumeric() || matches!(c, '.' | '-' | '_'))
        .take(32)
        .collect();
    format!(
        r#"<?xml version="1.0" standalone='no'?>
<!DOCTYPE service-group SYSTEM "avahi-service.dtd">
<!-- Generated by mistd; carries non-secret identity only (design 11 §2). -->
<service-group>
  <name replace-wildcards="yes">Mist on %h</name>
  <service>
    <type>_mist._tcp</type>
    <port>{tcp_port}</port>
    <txt-record>v=1</txt-record>
    <txt-record>uuid={uuid}</txt-record>
    <txt-record>tx=tcp</txt-record>
    <txt-record>shares={shares}</txt-record>
    <txt-record>kver={kver}</txt-record>
  </service>
</service-group>
"#,
        uuid = mist_proto::vm_uuid_hex(uuid),
    )
}

/// Publish the `_mist._tcp` advert by writing avahi's service file. Best-effort: a failure (no
/// avahi, read-only `/etc`) is logged, never fatal — discovery degrades to the host's lease/ARP
/// scan + authenticated probe (design 11 §10).
pub fn publish_avahi(
    service_file: &Path,
    uuid: &[u8; 16],
    tcp_port: Option<u16>,
    shares: usize,
    kver: &str,
) {
    if service_file.as_os_str().is_empty() {
        return; // explicitly disabled
    }
    let Some(port) = tcp_port else {
        tracing::info!(
            "no tcp listener configured; skipping _mist._tcp advert (host can still lease-scan)"
        );
        return;
    };
    let xml = avahi_service_xml(uuid, port, shares, kver);
    if let Some(dir) = service_file.parent()
        && !dir.exists()
    {
        // avahi's services dir is absent on a box without avahi-daemon installed; nothing watches
        // it, so don't create it (a stray file would just confuse a later install).
        tracing::info!(dir = %dir.display(), "avahi services dir absent; advert not published");
        return;
    }
    match std::fs::write(service_file, xml) {
        Ok(()) => {
            tracing::info!(file = %service_file.display(), port, "published _mist._tcp advert")
        }
        Err(e) => {
            tracing::warn!(error = %e, file = %service_file.display(), "avahi advert write failed")
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn vmid_persists_across_loads() {
        let dir = tempfile::tempdir().unwrap();
        let p = dir.path().join("vmid");
        let a = load_or_create_vmid(&p).unwrap();
        let b = load_or_create_vmid(&p).unwrap();
        assert_eq!(a, b, "vm_uuid must be stable across loads");
        // Persisted form is hex + newline.
        let on_disk = std::fs::read_to_string(&p).unwrap();
        assert_eq!(on_disk.trim(), mist_proto::vm_uuid_hex(&a));
    }

    #[test]
    fn vmid_remints_on_corrupt() {
        let dir = tempfile::tempdir().unwrap();
        let p = dir.path().join("vmid");
        std::fs::write(&p, b"not-valid-hex\n").unwrap();
        let u = load_or_create_vmid(&p).unwrap();
        // Re-reading the now-rewritten file yields the same minted value.
        assert_eq!(load_or_create_vmid(&p).unwrap(), u);
    }

    #[test]
    fn avahi_xml_has_identity_and_no_secret() {
        let u = [0xab; 16];
        let xml = avahi_service_xml(&u, 6478, 3, "6.1.0-debian");
        assert!(xml.contains("_mist._tcp"));
        assert!(xml.contains("<port>6478</port>"));
        assert!(xml.contains(&format!("uuid={}", mist_proto::vm_uuid_hex(&u))));
        assert!(xml.contains("tx=tcp"));
        assert!(xml.contains("shares=3"));
        assert!(xml.contains("kver=6.1.0-debian"));
        // A secret must never appear in a multicast advert.
        assert!(!xml.to_lowercase().contains("token"));
    }
}
